- name: Add ZeroTier gpg key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ zerotier_gpg_url }}"
    fingerprint: "{{ zerotier_gpg_fingerprint }}"

- name: Add ZeroTier repo for RHEL/CentOS
  ansible.builtin.yum_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    baseurl: https://download.zerotier.com/redhat/el/$releasever
    gpgcheck: true
    enabled: true
  register: zerotier_repo
  when: ansible_facts['distribution'] != "Fedora"

- name: Add zerotier repo for Fedora
  ansible.builtin.yum_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    baseurl: https://download.zerotier.com/redhat/fc/$releasever
    gpgcheck: true
    enabled: true
  register: zerotier_repo
  when: ansible_facts['distribution'] == "Fedora"
