---
- name: Install and enable zerotier-one tasks
  ansible.builtin.include_tasks: install/{{ ansible_facts['os_family'] }}.yml
  tags:
    - installation
    - repositories

- name: Install and enable zerotier-one
  when:
    - zerotier_repo is not defined or zerotier_repo is succeeded
    - not ansible_check_mode
  tags:
    - installation
    - packages
  block:
    - name: Install zerotier-one
      ansible.builtin.package:
        name: zerotier-one
        state: present
        update_cache: true
      register: zerotier_client

    - name: Start zerotier-one service
      ansible.builtin.service:
        name: zerotier-one
        state: started
      when:
        - zerotier_client is succeeded
      notify:
        - enable zerotier-one

    - name: Create facts.d
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory

    - name: Install zerotier custom facts
      ansible.builtin.copy:
        src: zerotier.fact.py
        dest: /etc/ansible/facts.d/zerotier.fact
        mode: "0755"

    - name: Re-gather facts
      ansible.builtin.setup: ~
