---
- name: Tasks file install.yml
  ansible.builtin.import_tasks: install.yml
  when:
    - not skip_install | default(false) | bool

- name: Update, re-gather ansible_local facts
  block:
    - name: Update ansible_local facts
      ansible.builtin.script: set_facts.sh

    - name: Re-gather ansible_local facts
      ansible.builtin.setup:
        filter: ansible_local

- name: Tasks file authorize_node.yml
  ansible.builtin.import_tasks: authorize_node.yml
  when:
    - zerotier_api_accesstoken != ''
    - ansible_local['zerotier']['node_id'] is defined

- name: Tasks file join_network.yml
  ansible.builtin.import_tasks: join_network.yml
  when:
    - zerotier_network_id is defined

- name: Tasks file settings.yml
  ansible.builtin.import_tasks: settings.yml
  when:
    - zerotier_network_id is defined
