---
- name: Set network configuration
  ansible.builtin.command: |
    zerotier-cli set {{ zerotier_network_id }} allowManaged={{ zerotier_allow_managed | default("1") }}
    allowGlobal={{ zerotier_allow_global | default("0") }} allowDefault={{ zerotier_allow_default | default("0") }}
    allowDNS={{ zerotier_allow_dns | default("0") }}
  tags:
    - configuration
# TODO: Module is not idempotent
