---
# handlers file for ansible-role-zerotier
- name: Start zerotier-one
  ansible.builtin.service:
    name: zerotier-one
    state: started

- name: Stop zerotier-one
  ansible.builtin.service:
    name: zerotier-one
    state: stopped

- name: Restart zerotier-one
  ansible.builtin.service:
    name: zerotier-one
    state: restarted

- name: Enable zerotier-one
  ansible.builtin.service:
    name: zerotier-one
    enabled: true
